// auto-chat.js
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc } from 'firebase/firestore';
import fetch from 'node-fetch';

const firebaseConfig = {
    apiKey: "AIzaSyARMz0K5u5HLUWBeS3s_Ma0ttBuZzyHU3k",
    authDomain: "llmasajudgde.firebaseapp.com",
    projectId: "llmasajudgde",
    storageBucket: "llmasajudgde.firebasestorage.app",
    messagingSenderId: "186361069930",
    appId: "1:186361069930:web:12622be3eb4447f9826513"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const questions = [
    "夜泣きが続いて困っています",
    "離乳食の進め方について教えてください",
    "子どもの発熱時の対処法を教えてください",
    "トイレトレーニングのコツは？",
    "イヤイヤ期の対処法について"
];
async function processQuestion(question, maxRetries = 3) {
    let attempts = 0;
    while (attempts < maxRetries) {
        try {
            const sessionId = `auto-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
            
            const msgDoc = await addDoc(collection(db, "chatLogs"), {
                content: question,
                type: "user",
                sessionId: sessionId,
                timestamp: new Date()
            });

            const response = await fetch("http://localhost:3000/api/chat", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-Session-ID": sessionId
                },
                body: JSON.stringify({
                    userMessage: question,
                    conversationSummary: ""
                })
            });

            if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);

            const data = await response.json();
            
            const aiMessageContent = {
                message: data.reply,
                messageType: data.type,
                timestamp: new Date().toISOString()
            };

            await addDoc(collection(db, "chatLogs"), {
                content: JSON.stringify(aiMessageContent),
                type: "ai",
                sessionId: sessionId,
                timestamp: new Date()
            });

            await addDoc(collection(db, "sessionSummaries"), {
                sessionId: sessionId,
                chatHistory: [
                    {
                        content: question,
                        type: "user",
                        timestamp: new Date().toISOString()
                    },
                    {
                        content: data.reply,
                        type: "ai",
                        messageType: data.type,
                        timestamp: new Date().toISOString()
                    }
                ],
                conversationSummary: data.summary,
                autoGenerated: true,
                timestamp: new Date()
            });

            console.log(`✅ 成功: "${question}"`);
            return true;

        } catch (error) {
            attempts++;
            console.error(`❌ 失敗 (${attempts}/${maxRetries}): "${question}"`, error);
            
            if (attempts < maxRetries) {
                const waitTime = Math.pow(2, attempts) * 1000;
                console.log(`⏳ ${waitTime/1000}秒後に再試行...`);
                await new Promise(resolve => setTimeout(resolve, waitTime));
            }
        }
    }
    return false;
}

async function simulateChat() {
    console.log(`=== 開始 - ${questions.length}件 ===`);
    let processed = 0;
    let failed = 0;

    for (let i = 0; i < questions.length; i++) {
        const question = questions[i];
        console.log(`\n[${i + 1}/${questions.length}]`);
        
        const success = await processQuestion(question);
        success ? processed++ : failed++;
        
        if (i < questions.length - 1) {
            await new Promise(resolve => setTimeout(resolve, 2000));
        }
    }

    console.log(`\n=== 完了: 成功=${processed}, 失敗=${failed} ===`);
}

simulateChat().catch(console.error);